#!/usr/bin/env bash
# NGINX config
#Nginx must be running, and listening on port 80 of all the server’s active IPv4 IPs 
sudo sed -i "s/sites-enabled/sites-available/" /etc/nginx/nginx.conf
sudo service nginx reload
sudo service nginx restart
