#!/usr/bin/env bash
# Display Holberton school 10 times but with a while

x=1
while [ $x -le 10 ]
do
    echo "Holberton School"
    if [ $x -eq 4 ]
    then
        echo "bad luck"
    elif [$x -eq 8]
    then
        echo "good luck"
    fi
    x=$((x+1))
done
